---
- name: Setup Desktop
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - ansible.builtin.set_fact:
        tech_bin_dir: "$HOME/tech/bin"
        operating_system: "{{ ansible_facts['system'] | lower }}"
    - ansible.builtin.set_fact:
        arm_or_amd: "amd64"
      when: ansible_facts['architecture'] == 'x86_64'
    - ansible.builtin.set_fact:
        arm_or_amd: "arm64"
      when: ansible_facts['architecture'] == 'aarch64'

    - name: Install pip requirements
      ansible.builtin.pip:
        name: "{{ pip_module }}"
      with_items:
        - github3.py
        - virtualenv
      loop_control:
        loop_var: pip_module

    - ansible.builtin.include_tasks: "{{ ansible_tasks }}"
      with_fileglob:
        - tasks/*
      loop_control:
        loop_var: ansible_tasks
