---
- name: Setup Desktop
  hosts: localhost
  connection: local
  gather_facts: true
  vars_prompt:
    - name: skip_installed
      prompt: skip installed binaries? (y/n)
      private: false

  tasks:
    - ansible.builtin.set_fact:
        tech_bin_dir: "{{ ansible_facts.user_dir }}/tech/bin"
        project_dir: "{{ ansible_facts.user_dir }}/projects"
        operating_system: "{{ ansible_facts['system'] | lower }}"
    - ansible.builtin.set_fact:
        arm_or_amd: "amd64"
      when: ansible_facts['architecture'] == 'x86_64'
    - ansible.builtin.set_fact:
        arm_or_amd: "arm64"
      when: ansible_facts['architecture'] == 'aarch64' or ansible_facts['architecture'] == 'arm64'

    - name: Install pip requirements
      ansible.builtin.pip:
        name: "{{ pip_module }}"
      with_items:
        - github3.py
        - virtualenv
      loop_control:
        loop_var: pip_module

    - name: Setup directories
      ansible.builtin.file:
        path: "{{ directories }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ tech_bin_dir }}"
        - "{{ project_dir }}"
        - "{{ ansible_facts.user_dir }}/.config/k9s"
        - "{{ ansible_facts.user_dir }}/.config/k9s/plugins"
        - "{{ ansible_facts.user_dir }}/.krew/bin"
      loop_control:
        loop_var: directories

    - name: Copy dotfiles
      ansible.builtin.copy:
        src: "{{ copy_files.source }}"
        dest: "{{ copy_files.destination }}"
      with_items:
        - source: files/dotfiles/.zshrc
          destination: "{{ ansible_facts.user_dir }}/.zshrc"
        - source: files/dotfiles/.p10k.zsh
          destination: "{{ ansible_facts.user_dir }}/.p10k.zsh"
        - source: files/dotfiles/.config/k9s/
          destination: "{{ ansible_facts.user_dir }}/.config/k9s/plugins/"
      loop_control:
        loop_var: copy_files

    - ansible.builtin.include_tasks: "{{ ansible_tasks }}"
      with_fileglob:
        - tasks/*
      loop_control:
        loop_var: ansible_tasks
