---
- name: Get latest release of cilium
  community.general.github_release:
    user: cilium
    repo: cilium-cli
    action: latest_release
  register: cilium_latest_release
- ansible.builtin.set_fact:
    cilium_url: https://github.com/cilium/cilium-cli/releases/download/{{ cilium_latest_release.tag }}/cilium-linux-{{ arm_or_amd }}.tar.gz
- name: Download cilium
  ansible.builtin.unarchive:
    src: "{{ cilium_url }}"
    dest: "{{ tech_bin_dir }}"
    remote_src: true
    include:
      - cilium
