---
- name: Get latest release of clusterctl
  community.general.github_release:
    user: kubernetes-sigs
    repo: cluster-api
    action: latest_release
  register: clusterctl_latest_release
- ansible.builtin.set_fact:
    clusterctl_url: https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ clusterctl_latest_release.tag }}/clusterctl-{{ operating_system }}-{{ arm_or_amd }}
- name: Download clusterctl
  ansible.builtin.get_url:
    url: "{{ clusterctl_url }}"
    dest: "{{ tech_bin_dir }}/clusterctl"
    mode: '0755'
