---
- name: Check if Crane is installed
  ansible.builtin.stat:
    path: "{{ tech_bin_dir }}/crane"
  register: crane_bin
- name: "Install Crane"
  when: skip_installed == "n" or (not crane_bin.stat.exists and skip_installed == "y")
  block:
    - name: Get crane releases
      ansible.builtin.uri:
        url: https://api.github.com/repos/google/go-containerregistry/releases/latest
        method: GET
        return_content: true
        status_code: 200
        body_format: json
      register: crane_release
    - name: Get latest crane release
      ansible.builtin.set_fact:
        crane_version: "{{ crane_release.json.tag_name }}"
    - ansible.builtin.set_fact:
        crane_url: "https://github.com/google/go-containerregistry/releases/download/{{ crane_version }}/go-containerregistry_{{ operating_system }}_{{ ansible_facts['architecture'] }}.tar.gz"
    - name: Download latest crane
      ansible.builtin.unarchive:
        src: "{{ crane_url }}"
        dest: "{{ tech_bin_dir }}"
        remote_src: true
        include:
          - crane
