---
- name: "Install RPMs"
  when: ansible_facts['os_family'] == 'RedHat'
  block:
    - name: Add the flathub flatpak repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user
    - name: Install from flatpak
      community.general.flatpak:
        name:
          - com.bambulab.BambuStudio
          - com.bitwarden.desktop
          - com.discordapp.Discord
          - com.spotify.Client
          - com.usebruno.Bruno
          - com.valvesoftware.Steam
          - org.gimp.GIMP
        state: present
        method: user