---
- name: Ensure GitHub3 Python Module
  ansible.builtin.pip:
    name: github3.py
- name: Get latest release of insomnia
  community.general.github_release:
    user: Kong
    repo: insomnia
    action: latest_release
  register: insomnia_latest_release
- ansible.builtin.set_fact:
    insomnia_url: "https://github.com/Kong/insomnia/releases/download/core%40{{ insomnia_latest_release.tag | replace('core@', '') }}/Insomnia.Core-{{ insomnia_latest_release.tag | replace('core@', '') }}.rpm"
- name: Install Insomnia
  ansible.builtin.dnf:
    name: "{{ insomnia_url }}"
    state: present
    disable_gpg_check: true
  become: true
