---
- name: "Install RPMs"
  when: "{{ ansible_facts['os_family'] == 'RedHat' }}"
  block:
  - set_fact:
      yum_repos:
        - name: gh-cli
          baseurl: https://cli.github.com/packages/rpm
          enabled: true
          gpgkey: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x23F3D4EA75716059
        - name: google-chrome
          baseurl: "https://dl.google.com/linux/chrome/rpm/stable/{{ ansible_facts['architecture'] }}"
          enabled: true
          gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        - name: google-cloud-cli
          baseurl: "https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-{{ ansible_facts['architecture'] }}"
          enabled: true
          gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        - name: hashicorp-stable
          # baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
          baseurl: https://rpm.releases.hashicorp.com/fedora/41/$basearch/stable
          enabled: true
          gpgkey: https://rpm.releases.hashicorp.com/gpg
        - name: visual-studio-code
          baseurl: https://packages.microsoft.com/yumrepos/vscode
          enabled: true
          gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name: Add repos
    ansible.builtin.yum_repository:
      name: "{{ item.name }}"
      description: "{{ item.name }}"
      baseurl: "{{ item.baseurl }}"
      enabled: "{{ item.enabled }}"
      gpgkey: "{{ item.gpgkey }}"
    with_items: "{{ yum_repos }}"
    become: true

  - name: Install RPMs
    ansible.builtin.dnf:
      name:
        - code
        - discord
        - fzf
        - jq
        - golang
        - gh
        - google-chrome-stable
        - google-cloud-cli
        - jq
        - packer
        - podman
        - python3
        - python3-pip
        - terraform
        - the_silver_searcher
        - vault
        - vim
        - zsh
      state: latest
    become: true
