---
- name: "Install RPMs"
  when: ansible_facts['os_family'] == 'RedHat'
  block:
  - set_fact:
      yum_repos:
        - name: gh-cli
          baseurl: https://cli.github.com/packages/rpm
          enabled: true
          gpgkey: https://cli.github.com/packages/githubcli-archive-keyring.asc
        - name: google-chrome
          baseurl: "https://dl.google.com/linux/chrome/rpm/stable/{{ ansible_facts['architecture'] }}"
          enabled: true
          gpgkey: https://dl.google.com/linux/linux_signing_key.pub
        - name: visual-studio-code
          baseurl: https://packages.microsoft.com/yumrepos/vscode
          enabled: true
          gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name: Add repos
    ansible.builtin.yum_repository:
      name: "{{ yum_repo.name }}"
      description: "{{ yum_repo.name }}"
      baseurl: "{{ yum_repo.baseurl }}"
      enabled: "{{ yum_repo.enabled }}"
      gpgkey: "{{ yum_repo.gpgkey }}"
    with_items: "{{ yum_repos }}"
    loop_control:
      loop_var: yum_repo
    become: true

  - name: Install RPMs
    ansible.builtin.dnf:
      name:
        - code
        - fastfetch
        - fzf
        - gh
        - golang
        - google-chrome-stable
        - jq
        - podman
        - python3
        - python3-pip
        - steam-devices
        - the_silver_searcher
        - vim
        - zsh
      state: latest
    become: true
